// ========================================
// NATIONAL TARGETS - ZONES D'INTERVENTION
// Réseau de maintenance sécurité incendie (extincteurs, BAES, désenfumage)
// Les données administratives (insee, epci, population, zones) proviennent de
// l'API Découpage administratif (Etalab / IGN) et sont réelles.
// ========================================

export interface NationalTarget {
    slug: string;
    name: string;
    heroTitle: string;
    geo: { lat: number; lng: number };
    price_start: number; // Prix maintenance à partir de
    top_places: string[]; // Zones d'intervention réelles (communes limitrophes)
    zip: string;
    tier: 'BIG5' | 'GOLDEN' | 'HUB' | 'STRATEGIC';
    heroImage?: string;
    // Identité administrative réelle de la commune (source : API Découpage
    // administratif, Etalab / IGN). Ces champs remplacent les faux quartiers
    // "Quartier Nord / Quartier Sud" qui étaient identiques sur 122 communes.
    insee?: string;
    epci?: string;
    population?: number;
    deptCode?: string;
    deptName?: string;
    regionName?: string;
    /** Communes limitrophes réelles, distances calculées depuis les coordonnées officielles */
    zones?: { nom: string; km: number }[];
}

export const NATIONAL_TARGETS: NationalTarget[] = [
    // ========================================
    // 👑 TIER 1: BIG 5 (60% du CA)
    // ========================================
    {
        slug: "paris",
        name: "Paris",
        heroTitle: "technicien Sécurité Incendie Paris (75)",
        geo: { lat: 48.8589, lng: 2.347 },
        price_start: 900.00,
        top_places: ["Paris 16", "Paris 17", "Le Marais", "Montmartre"],
        zip: "75001",
        tier: 'BIG5',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "lyon",
        name: "Lyon",
        heroTitle: "maintenance Sécurité Incendie Lyon",
        geo: { lat: 45.758, lng: 4.8351 },
        price_start: 890.00,
        top_places: ["Monts d'Or", "Presqu'île", "Part-Dieu", "Confluence"],
        zip: "69001",
        tier: 'BIG5',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "marseille",
        name: "Marseille",
        heroTitle: "Pose extincteur Marseille",
        geo: { lat: 43.2803, lng: 5.3806 },
        price_start: 850.00,
        top_places: ["Prado", "Corniche", "Vieux-Port", "Euroméditerranée"],
        zip: "13001",
        tier: 'BIG5',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "nice",
        name: "Nice",
        heroTitle: "technicien Incendie Nice",
        geo: { lat: 43.7032, lng: 7.2528 },
        price_start: 950.00,
        top_places: ["Promenade des Anglais", "Cimiez", "Mont Boron", "Carré d'Or"],
        zip: "06000",
        tier: 'BIG5',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "bordeaux",
        name: "Bordeaux",
        heroTitle: "Expert Sécurité Incendie Bordeaux",
        geo: { lat: 44.8624, lng: -0.5848 },
        price_start: 890.00,
        top_places: ["Chartrons", "Caudéran", "Le Bouscat", "Talence"],
        zip: "33000",
        tier: 'BIG5',
        heroImage: "https://Images.unsplash.com/photo-1559087867-ce4c91325525?q=80&w=2670&auto=format&fit=crop"
    },
    {
        slug: "toulouse",
        name: "Toulouse",
        heroTitle: "maintenance Extincteur Toulouse",
        geo: { lat: 43.6007, lng: 1.4328 },
        price_start: 850.00,
        top_places: ["Capitol", "Carmes", "Saint-Cyprien", "Balma"],
        zip: "31000",
        tier: 'BIG5',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },

    // ========================================
    // 💎 TIER 2: GOLDEN CITIES (Pouvoir d'achat Élevé)
    // ========================================
    {
        slug: "cannes",
        name: "Cannes",
        heroTitle: "matériel incendie Cannes & Mougins",
        geo: { lat: 43.5454, lng: 7.0152 },
        price_start: 1100.00,
        top_places: ["La Californie", "Croisette", "Super Cannes", "Mougins"],
        zip: "06150",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "aix-en-provence",
        name: "Aix-en-Provence",
        heroTitle: "maintenance extincteur Aix & Luberon",
        geo: { lat: 43.536, lng: 5.3879 },
        price_start: 950.00,
        top_places: ["Centre Historique", "Puyricard", "Les Milles", "Tholonet"],
        zip: "13080",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "antibes",
        name: "Antibes",
        heroTitle: "Sécurité Incendie Antibes & Sophia",
        geo: { lat: 43.5823, lng: 7.1048 },
        price_start: 980.00,
        top_places: ["Cap d'Antibes", "Juan-les-Pins", "Biot", "Sophia-Antipolis"],
        zip: "06160",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "neuilly-sur-seine",
        name: "Neuilly-sur-Seine",
        heroTitle: "maintenance extincteur Neuilly 92",
        geo: { lat: 48.8862, lng: 2.2651 },
        price_start: 1200.00,
        top_places: ["Saint-James", "Sablons", "Bagatelle", "Ile de la Jatte"],
        zip: "92200",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "lille",
        name: "Lille",
        heroTitle: "technicien extincteur Incendie Lille",
        geo: { lat: 50.6311, lng: 3.0468 },
        price_start: 890.00,
        top_places: ["Vieux-Lille", "Marcq-en-Barœul", "Bondues", "Lambersart"],
        zip: "59000",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "strasbourg",
        name: "Strasbourg",
        heroTitle: "extincteur Strasbourg",
        geo: { lat: 48.5691, lng: 7.7621 },
        price_start: 890.00,
        top_places: ["Orangerie", "Robertsau", "Contades", "Neudorf"],
        zip: "67000",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "nantes",
        name: "Nantes",
        heroTitle: "maintenance extincteur Nantes",
        geo: { lat: 47.2382, lng: -1.5603 },
        price_start: 850.00,
        top_places: ["Procé", "Monselet", "Saint-Félix", "Carquefou"],
        zip: "44000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "rennes",
        name: "Rennes",
        heroTitle: "Sécurité Incendie Rennes",
        geo: { lat: 48.1159, lng: -1.6884 },
        price_start: 850.00,
        top_places: ["Thabor", "Sévigné", "Saint-Grégoire", "Cesson-Sévigné"],
        zip: "35000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "montpellier",
        name: "Montpellier",
        heroTitle: "maintenance extincteur Montpellier",
        geo: { lat: 43.61, lng: 3.8742 },
        price_start: 850.00,
        top_places: ["Port Marianne", "Aiguelongue", "Castelnau-le-Lez", "Lattes"],
        zip: "34000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "annecy",
        name: "Annecy",
        heroTitle: "Sécurité Incendie Annecy & 74",
        geo: { lat: 45.9024, lng: 6.1264 },
        price_start: 950.00,
        top_places: ["Annecy-le-Vieux", "Veyrier-du-Lac", "Sevrier", "Pringy"],
        zip: "74000",
        tier: 'GOLDEN',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "toulon",
        name: "Toulon",
        heroTitle: "technicien Sécurité Incendie Toulon",
        geo: { lat: 43.1364, lng: 5.9334 },
        price_start: 950.00,
        top_places: ["Mourillon", "Le Mont Faron", "Cap Brun", "Siblas"],
        zip: "83000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "avignon",
        name: "Avignon",
        heroTitle: "maintenance extincteur Avignon & Vaucluse",
        geo: { lat: 43.9416, lng: 4.8333 },
        price_start: 900.00,
        top_places: ["Palais des Papes", "Villeneuve-lès-Avignon", "Le Pontet", "Montfavet"],
        zip: "84000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "reims",
        name: "Reims",
        heroTitle: "matériel incendie Reims",
        geo: { lat: 49.2535, lng: 4.0551 },
        price_start: 890.00,
        top_places: ["Cathédrale", "Cormontreuil", "Tinqueux", "Bétheny"],
        zip: "51100",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "dijon",
        name: "Dijon",
        heroTitle: "maintenance extincteur Dijon & 21",
        geo: { lat: 47.3319, lng: 5.0322 },
        price_start: 890.00,
        top_places: ["Centre Historique", "Toison d'Or", "Fontaine-lès-Dijon", "Talant"],
        zip: "21000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "rouen",
        name: "Rouen",
        heroTitle: "technicien Incendie Rouen",
        geo: { lat: 49.4412, lng: 1.0912 },
        price_start: 890.00,
        top_places: ["Rive Droite", "Mont-Saint-Aignan", "Bois-Guillaume", "Sotteville"],
        zip: "76000",
        tier: 'HUB',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },

    // ========================================
    // ✈️ TIER 4: STRATEGIC SPOTS (Zones Périurbaines Riches)
    // ========================================
    {
        slug: "roissy-en-france",
        name: "Roissy-en-France",
        heroTitle: "maintenance extincteur Roissy & 95",
        geo: { lat: 49.0036, lng: 2.5188 },
        price_start: 950.00,
        top_places: ["Tremblay-en-France", "Villepinte", "Goussainville", "Louvres"],
        zip: "95700",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "orly",
        name: "Orly",
        heroTitle: "Sécurité Incendie Orly & Sud 94",
        geo: { lat: 48.7402, lng: 2.403 },
        price_start: 950.00,
        top_places: ["Thiais", "Rungis", "Choisy-le-Roi", "Athis-Mons"],
        zip: "94310",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "beauvais",
        name: "Beauvais",
        heroTitle: "technicien extincteur Beauvais",
        geo: { lat: 49.4425, lng: 2.0877 },
        price_start: 900.00,
        top_places: ["Centre-Ville", "Tillé", "Allonne", "Voisinlieu"],
        zip: "60000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "saint-exupery",
        name: "Saint-Exupéry",
        heroTitle: "maintenance extincteur Est Lyonnais",
        geo: { lat: 44.6336, lng: -0.1009 },
        price_start: 950.00,
        top_places: ["Saint-Laurent-de-Mure", "Genas", "Meyzieu", "Pusignan"],
        zip: "33190",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "cagnes-sur-mer",
        name: "Cagnes-sur-Mer",
        heroTitle: "Sécurité Incendie Cagnes & St-Laurent",
        geo: { lat: 43.6712, lng: 7.1502 },
        price_start: 1000.00,
        top_places: ["Cros-de-Cagnes", "Saint-Laurent-du-Var", "Villeneuve-Loubet", "La Colle-sur-Loup"],
        zip: "06800",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "pays-de-gex",
        name: "Pays de Gex",
        heroTitle: "maintenance extincteur Frontière Suisse",
        geo: { lat: 46.3333, lng: 6.0667 },
        price_start: 1200.00,
        top_places: ["Ferney-Voltaire", "Divonne-les-Bains", "Saint-Genis-Pouilly", "Gex"],
        zip: "01170",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "mulhouse",
        name: "Mulhouse",
        heroTitle: "Sécurité Incendie Mulhouse & 3 Frontières",
        geo: { lat: 47.7526, lng: 7.3255 },
        price_start: 890.00,
        top_places: ["Saint-Louis", "Rixheim", "Kingersheim", "Wittenheim"],
        zip: "68100",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "marne-la-vallee",
        name: "Marne-la-Vallée",
        heroTitle: "maintenance extincteur Marne-la-Vallée",
        geo: { lat: 48.85, lng: 2.6 },
        price_start: 950.00,
        top_places: ["Chessy", "Serris", "Bussy-Saint-Georges", "Val d'Europe"],
        zip: "77400",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    // ========================================
    // 🌍 TIER 5: SOUTH-WEST EXPANSION
    // ========================================
    {
        slug: "pau",
        name: "Pau",
        heroTitle: "technicien matériel incendie Pau (64)",
        geo: { lat: 43.3219, lng: -0.3435 },
        price_start: 850.00,
        top_places: ["Centre-Ville", "Trespoey", "Billère", "Lons"],
        zip: "64000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "bayonne",
        name: "Bayonne",
        heroTitle: "maintenance extincteur Pays Basque (Bayonne)",
        geo: { lat: 43.4844, lng: -1.4611 },
        price_start: 890.00,
        top_places: ["Grand Bayonne", "Petit Bayonne", "Anglet", "Saint-Esprit"],
        zip: "64100",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "biarritz",
        name: "Biarritz",
        heroTitle: "technicien Incendie Biarritz",
        geo: { lat: 43.4709, lng: -1.5557 },
        price_start: 950.00,
        top_places: ["Côte des Basques", "Milady", "Saint-Charles", "La Négresse"],
        zip: "64200",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "tarbes",
        name: "Tarbes",
        heroTitle: "Pose matériel incendie Tarbes",
        geo: { lat: 43.2387, lng: 0.0653 },
        price_start: 850.00,
        top_places: ["Centre-Ville", "Ormeau", "Aureilhan", "Laloubère"],
        zip: "65000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "agen",
        name: "Agen",
        heroTitle: "Maintenance Incendie Agen (47)",
        geo: { lat: 44.201, lng: 0.6302 },
        price_start: 850.00,
        top_places: ["Centre-Ville", "Ermitage", "Le Passage", "Boé"],
        zip: "47000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "montauban",
        name: "Montauban",
        heroTitle: "Expert Sécurité Incendie Montauban",
        geo: { lat: 44.0217, lng: 1.3646 },
        price_start: 850.00,
        top_places: ["Centre Historique", "Villebourbon", "Saint-Martial", "Sapiac"],
        zip: "82000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "albi",
        name: "Albi",
        heroTitle: "technicien matériel incendie Albi",
        geo: { lat: 43.929, lng: 2.1323 },
        price_start: 850.00,
        top_places: ["Centre Historique", "Leuc", "Saint-Juéry", "Lescure-d'Albigeois"],
        zip: "81000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "castres",
        name: "Castres",
        heroTitle: "maintenance extincteur Castres & Tarn",
        geo: { lat: 43.6132, lng: 2.2448 },
        price_start: 850.00,
        top_places: ["Lameilhé", "Aillot", "Burlats", "Lagarrigue"],
        zip: "81100",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "mont-de-marsan",
        name: "Mont-de-Marsan",
        heroTitle: "technicien matériel incendie Landes (40)",
        geo: { lat: 43.8931, lng: -0.5009 },
        price_start: 850.00,
        top_places: ["Centre-Ville", "Saint-Médard", "Saint-Jean-d'Août", "Saint-Pierre-du-Mont"],
        zip: "40000",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "dax",
        name: "Dax",
        heroTitle: "Expert matériel incendie Dax & Sud Landes",
        geo: { lat: 43.7025, lng: -1.0637 },
        price_start: 850.00,
        top_places: ["Centre-Ville", "Saint-Vincent-de-Paul", "Narrosse", "Saint-Paul-lès-Dax"],
        zip: "40100",
        tier: 'STRATEGIC',
        heroImage: "/images/realizations/hero-extincteur.jpg"
    },
    {
        slug: "saint-etienne",
        name: "Saint-Étienne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.4241, lng: 4.3665 },
        price_start: 90,
        top_places: ["La Ricamarie", "Roche-la-Molière", "Saint-Genest-Lerpt", "Le Chambon-Feugerolles"],
        zones: [{ nom: "La Ricamarie", km: 2.2 }, { nom: "Roche-la-Molière", km: 3.0 }, { nom: "Saint-Genest-Lerpt", km: 4.2 }, { nom: "Le Chambon-Feugerolles", km: 4.3 }],
        zip: "42000",
        tier: 'HUB',
        insee: "42218",
        epci: "Saint-Étienne Métropole",
        population: 173136,
        deptCode: "42", deptName: "Loire",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "le-havre",
        name: "Le Havre",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.4958, lng: 0.1312 },
        price_start: 90,
        top_places: ["Sainte-Adresse", "Harfleur", "Fontaine-la-Mallet", "Gonfreville-l'Orcher"],
        zones: [{ nom: "Sainte-Adresse", km: 4.1 }, { nom: "Harfleur", km: 5.1 }, { nom: "Fontaine-la-Mallet", km: 5.1 }, { nom: "Gonfreville-l'Orcher", km: 6.7 }],
        zip: "76600",
        tier: 'HUB',
        insee: "76351",
        epci: "CU Le Havre Seine Métropole",
        population: 166687,
        deptCode: "76", deptName: "Seine-Maritime",
        regionName: "Normandie",
    },
    {
        slug: "grenoble",
        name: "Grenoble",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.1842, lng: 5.7155 },
        price_start: 90,
        top_places: ["Fontaine", "La Tronche", "Seyssinet-Pariset", "Saint-Martin-le-Vinoux"],
        zones: [{ nom: "Fontaine", km: 3.3 }, { nom: "La Tronche", km: 3.8 }, { nom: "Seyssinet-Pariset", km: 3.8 }, { nom: "Saint-Martin-le-Vinoux", km: 3.8 }],
        zip: "38000",
        tier: 'HUB',
        insee: "38185",
        epci: "Grenoble-Alpes-Métropole",
        population: 156140,
        deptCode: "38", deptName: "Isère",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "angers",
        name: "Angers",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.4819, lng: -0.5629 },
        price_start: 90,
        top_places: ["Avrillé", "Beaucouzé", "Écouflant", "Sainte-Gemmes-sur-Loire"],
        zones: [{ nom: "Avrillé", km: 3.7 }, { nom: "Beaucouzé", km: 5.5 }, { nom: "Écouflant", km: 5.7 }, { nom: "Sainte-Gemmes-sur-Loire", km: 5.8 }],
        zip: "49000",
        tier: 'HUB',
        insee: "49007",
        epci: "CU Angers Loire Métropole",
        population: 159022,
        deptCode: "49", deptName: "Maine-et-Loire",
        regionName: "Pays de la Loire",
    },
    {
        slug: "nimes",
        name: "Nîmes",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 43.8322, lng: 4.3429 },
        price_start: 90,
        top_places: ["Caveirac", "Caissargues", "Milhaud", "Rodilhan"],
        zones: [{ nom: "Caveirac", km: 5.7 }, { nom: "Caissargues", km: 5.9 }, { nom: "Milhaud", km: 6.1 }, { nom: "Rodilhan", km: 7.3 }],
        zip: "30000",
        tier: 'HUB',
        insee: "30189",
        epci: "CA de Nîmes Métropole",
        population: 151839,
        deptCode: "30", deptName: "Gard",
        regionName: "Occitanie",
    },
    {
        slug: "villeurbanne",
        name: "Villeurbanne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.7719, lng: 4.8898 },
        price_start: 90,
        top_places: ["Vaulx-en-Velin", "Caluire-et-Cuire", "Bron", "Lyon"],
        zones: [{ nom: "Vaulx-en-Velin", km: 2.8 }, { nom: "Caluire-et-Cuire", km: 4.3 }, { nom: "Bron", km: 4.4 }, { nom: "Lyon", km: 4.5 }],
        zip: "69100",
        tier: 'HUB',
        insee: "69266",
        epci: "Métropole de Lyon",
        population: 163684,
        deptCode: "69", deptName: "Rhône",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "clermont-ferrand",
        name: "Clermont-Ferrand",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.787, lng: 3.1127 },
        price_start: 90,
        top_places: ["Aubière", "Chamalières", "Durtol", "Beaumont"],
        zones: [{ nom: "Aubière", km: 4.1 }, { nom: "Chamalières", km: 4.3 }, { nom: "Durtol", km: 4.5 }, { nom: "Beaumont", km: 4.6 }],
        zip: "63000",
        tier: 'HUB',
        insee: "63113",
        epci: "Clermont Auvergne Métropole",
        population: 146351,
        deptCode: "63", deptName: "Puy-de-Dôme",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "le-mans",
        name: "Le Mans",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.9819, lng: 0.1957 },
        price_start: 90,
        top_places: ["Rouillon", "Allonnes", "Arnage", "Coulaines"],
        zones: [{ nom: "Rouillon", km: 4.4 }, { nom: "Allonnes", km: 4.6 }, { nom: "Arnage", km: 5.7 }, { nom: "Coulaines", km: 6.0 }],
        zip: "72000",
        tier: 'HUB',
        insee: "72181",
        epci: "CU Le Mans Métropole",
        population: 146249,
        deptCode: "72", deptName: "Sarthe",
        regionName: "Pays de la Loire",
    },
    {
        slug: "brest",
        name: "Brest",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.4085, lng: -4.4996 },
        price_start: 90,
        top_places: ["Bohars", "Guilers", "Gouesnou", "Le Relecq-Kerhuon"],
        zones: [{ nom: "Bohars", km: 2.8 }, { nom: "Guilers", km: 4.8 }, { nom: "Gouesnou", km: 5.1 }, { nom: "Le Relecq-Kerhuon", km: 7.3 }],
        zip: "29200",
        tier: 'HUB',
        insee: "29019",
        epci: "Brest Métropole",
        population: 142346,
        deptCode: "29", deptName: "Finistère",
        regionName: "Bretagne",
    },
    {
        slug: "tours",
        name: "Tours",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.3943, lng: 0.6949 },
        price_start: 90,
        top_places: ["Saint-Pierre-des-Corps", "Saint-Cyr-sur-Loire", "La Riche", "Saint-Avertin"],
        zones: [{ nom: "Saint-Pierre-des-Corps", km: 3.0 }, { nom: "Saint-Cyr-sur-Loire", km: 4.0 }, { nom: "La Riche", km: 4.6 }, { nom: "Saint-Avertin", km: 5.3 }],
        zip: "37000",
        tier: 'HUB',
        insee: "37261",
        epci: "Tours Métropole Val de Loire",
        population: 139259,
        deptCode: "37", deptName: "Indre-et-Loire",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "amiens",
        name: "Amiens",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.8987, lng: 2.2847 },
        price_start: 90,
        top_places: ["Rivery", "Dreuil-lès-Amiens", "Pont-de-Metz", "Salouël"],
        zones: [{ nom: "Rivery", km: 4.1 }, { nom: "Dreuil-lès-Amiens", km: 4.2 }, { nom: "Pont-de-Metz", km: 4.4 }, { nom: "Salouël", km: 4.8 }],
        zip: "80000",
        tier: 'HUB',
        insee: "80021",
        epci: "CA Amiens Métropole",
        population: 136449,
        deptCode: "80", deptName: "Somme",
        regionName: "Hauts-de-France",
    },
    {
        slug: "limoges",
        name: "Limoges",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.8567, lng: 1.226 },
        price_start: 90,
        top_places: ["Couzeix", "Isle", "Chaptelat", "Panazol"],
        zones: [{ nom: "Couzeix", km: 3.3 }, { nom: "Isle", km: 6.1 }, { nom: "Chaptelat", km: 6.7 }, { nom: "Panazol", km: 7.6 }],
        zip: "87000",
        tier: 'HUB',
        insee: "87085",
        epci: "CU Limoges Métropole",
        population: 129937,
        deptCode: "87", deptName: "Haute-Vienne",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "perpignan",
        name: "Perpignan",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 42.699, lng: 2.9045 },
        price_start: 90,
        top_places: ["Cabestany", "Bompas", "Saint-Estève", "Pia"],
        zones: [{ nom: "Cabestany", km: 4.3 }, { nom: "Bompas", km: 4.4 }, { nom: "Saint-Estève", km: 5.2 }, { nom: "Pia", km: 5.8 }],
        zip: "66000",
        tier: 'HUB',
        insee: "66136",
        epci: "CU Perpignan Méditerranée Métropole",
        population: 121616,
        deptCode: "66", deptName: "Pyrénées-Orientales",
        regionName: "Occitanie",
    },
    {
        slug: "besancon",
        name: "Besançon",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.2602, lng: 6.0123 },
        price_start: 90,
        top_places: ["École-Valentin", "Pirey", "Chalezeule", "Miserey-Salines"],
        zones: [{ nom: "École-Valentin", km: 2.4 }, { nom: "Pirey", km: 3.2 }, { nom: "Chalezeule", km: 4.2 }, { nom: "Miserey-Salines", km: 4.6 }],
        zip: "25000",
        tier: 'HUB',
        insee: "25056",
        epci: "CU Grand Besançon Métropole",
        population: 118489,
        deptCode: "25", deptName: "Doubs",
        regionName: "Bourgogne-Franche-Comté",
    },
    {
        slug: "metz",
        name: "Metz",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.1048, lng: 6.1962 },
        price_start: 90,
        top_places: ["Montigny-lès-Metz", "Saint-Julien-lès-Metz", "Longeville-lès-Metz", "Peltre"],
        zones: [{ nom: "Montigny-lès-Metz", km: 3.1 }, { nom: "Saint-Julien-lès-Metz", km: 3.8 }, { nom: "Longeville-lès-Metz", km: 3.8 }, { nom: "Peltre", km: 4.1 }],
        zip: "57000",
        tier: 'HUB',
        insee: "57463",
        epci: "Metz Métropole",
        population: 122572,
        deptCode: "57", deptName: "Moselle",
        regionName: "Grand Est",
    },
    {
        slug: "orleans",
        name: "Orléans",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.8734, lng: 1.9122 },
        price_start: 90,
        top_places: ["Saint-Jean-le-Blanc", "Olivet", "Saint-Denis-en-Val", "Saint-Jean-de-la-Ruelle"],
        zones: [{ nom: "Saint-Jean-le-Blanc", km: 1.9 }, { nom: "Olivet", km: 2.5 }, { nom: "Saint-Denis-en-Val", km: 4.5 }, { nom: "Saint-Jean-de-la-Ruelle", km: 5.1 }],
        zip: "45000",
        tier: 'HUB',
        insee: "45234",
        epci: "Orléans Métropole",
        population: 116357,
        deptCode: "45", deptName: "Loiret",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "caen",
        name: "Caen",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.1846, lng: -0.3722 },
        price_start: 90,
        top_places: ["Hérouville-Saint-Clair", "Bretteville-sur-Odon", "Saint-Contest", "Louvigny"],
        zones: [{ nom: "Hérouville-Saint-Clair", km: 3.6 }, { nom: "Bretteville-sur-Odon", km: 3.8 }, { nom: "Saint-Contest", km: 3.8 }, { nom: "Louvigny", km: 3.9 }],
        zip: "14000",
        tier: 'HUB',
        insee: "14118",
        epci: "CU Caen la Mer",
        population: 109400,
        deptCode: "14", deptName: "Calvados",
        regionName: "Normandie",
    },
    {
        slug: "nancy",
        name: "Nancy",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.6881, lng: 6.1734 },
        price_start: 90,
        top_places: ["Saint-Max", "Maxéville", "Vandœuvre-lès-Nancy", "Jarville-la-Malgrange"],
        zones: [{ nom: "Saint-Max", km: 3.0 }, { nom: "Maxéville", km: 3.2 }, { nom: "Vandœuvre-lès-Nancy", km: 3.3 }, { nom: "Jarville-la-Malgrange", km: 3.3 }],
        zip: "54000",
        tier: 'HUB',
        insee: "54395",
        epci: "Métropole du Grand Nancy",
        population: 103671,
        deptCode: "54", deptName: "Meurthe-et-Moselle",
        regionName: "Grand Est",
    },
    {
        slug: "argenteuil",
        name: "Argenteuil",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9501, lng: 2.2478 },
        price_start: 90,
        top_places: ["Sannois", "Colombes", "Saint-Gratien", "Gennevilliers"],
        zones: [{ nom: "Sannois", km: 2.6 }, { nom: "Colombes", km: 3.1 }, { nom: "Saint-Gratien", km: 3.4 }, { nom: "Gennevilliers", km: 3.6 }],
        zip: "95100",
        tier: 'HUB',
        insee: "95018",
        epci: "Métropole du Grand Paris",
        population: 106130,
        deptCode: "95", deptName: "Val-d'Oise",
        regionName: "Île-de-France",
    },
    {
        slug: "montreuil",
        name: "Montreuil",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8637, lng: 2.4491 },
        price_start: 90,
        top_places: ["Bagnolet", "Vincennes", "Fontenay-sous-Bois", "Romainville"],
        zones: [{ nom: "Bagnolet", km: 1.8 }, { nom: "Vincennes", km: 2.0 }, { nom: "Fontenay-sous-Bois", km: 2.3 }, { nom: "Romainville", km: 2.5 }],
        zip: "93100",
        tier: 'HUB',
        insee: "93048",
        epci: "Métropole du Grand Paris",
        population: 111934,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "roubaix",
        name: "Roubaix",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 50.6887, lng: 3.1843 },
        price_start: 90,
        top_places: ["Croix", "Lys-lez-Lannoy", "Lannoy", "Wattrelos"],
        zones: [{ nom: "Croix", km: 2.5 }, { nom: "Lys-lez-Lannoy", km: 3.0 }, { nom: "Lannoy", km: 3.1 }, { nom: "Wattrelos", km: 3.5 }],
        zip: "59100",
        tier: 'HUB',
        insee: "59512",
        epci: "Métropole Européenne de Lille",
        population: 98286,
        deptCode: "59", deptName: "Nord",
        regionName: "Hauts-de-France",
    },
    {
        slug: "tourcoing",
        name: "Tourcoing",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 50.721, lng: 3.1577 },
        price_start: 90,
        top_places: ["Mouvaux", "Neuville-en-Ferrain", "Roncq", "Roubaix"],
        zones: [{ nom: "Mouvaux", km: 2.4 }, { nom: "Neuville-en-Ferrain", km: 3.9 }, { nom: "Roncq", km: 4.0 }, { nom: "Roubaix", km: 4.1 }],
        zip: "59200",
        tier: 'HUB',
        insee: "59599",
        epci: "Métropole Européenne de Lille",
        population: 98772,
        deptCode: "59", deptName: "Nord",
        regionName: "Hauts-de-France",
    },
    {
        slug: "nanterre",
        name: "Nanterre",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8974, lng: 2.2018 },
        price_start: 90,
        top_places: ["Carrières-sur-Seine", "Puteaux", "Suresnes", "Bezons"],
        zones: [{ nom: "Carrières-sur-Seine", km: 2.3 }, { nom: "Puteaux", km: 3.2 }, { nom: "Suresnes", km: 3.2 }, { nom: "Bezons", km: 3.2 }],
        zip: "92000",
        tier: 'HUB',
        insee: "92050",
        epci: "Métropole du Grand Paris",
        population: 97783,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "vitry-sur-seine",
        name: "Vitry-sur-Seine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7893, lng: 2.3951 },
        price_start: 90,
        top_places: ["Alfortville", "Villejuif", "Ivry-sur-Seine", "Thiais"],
        zones: [{ nom: "Alfortville", km: 2.1 }, { nom: "Villejuif", km: 2.6 }, { nom: "Ivry-sur-Seine", km: 2.6 }, { nom: "Thiais", km: 3.3 }],
        zip: "94400",
        tier: 'HUB',
        insee: "94081",
        epci: "Métropole du Grand Paris",
        population: 93963,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "creteil",
        name: "Créteil",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7845, lng: 2.4523 },
        price_start: 90,
        top_places: ["Maisons-Alfort", "Alfortville", "Bonneuil-sur-Marne", "Choisy-le-Roi"],
        zones: [{ nom: "Maisons-Alfort", km: 2.1 }, { nom: "Alfortville", km: 2.6 }, { nom: "Bonneuil-sur-Marne", km: 3.3 }, { nom: "Choisy-le-Roi", km: 3.3 }],
        zip: "94000",
        tier: 'HUB',
        insee: "94028",
        epci: "Métropole du Grand Paris",
        population: 93397,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "poitiers",
        name: "Poitiers",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.5846, lng: 0.3715 },
        price_start: 90,
        top_places: ["Buxerolles", "Saint-Benoît", "Mignaloux-Beauvoir", "Biard"],
        zones: [{ nom: "Buxerolles", km: 2.4 }, { nom: "Saint-Benoît", km: 4.2 }, { nom: "Mignaloux-Beauvoir", km: 5.0 }, { nom: "Biard", km: 5.8 }],
        zip: "86000",
        tier: 'HUB',
        insee: "86194",
        epci: "CU du Grand Poitiers",
        population: 89916,
        deptCode: "86", deptName: "Vienne",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "dunkerque",
        name: "Dunkerque",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 51.0183, lng: 2.3431 },
        price_start: 90,
        top_places: ["Cappelle-la-Grande", "Grande-Synthe", "Coudekerque-Branche", "Armbouts-Cappel"],
        zones: [{ nom: "Cappelle-la-Grande", km: 3.2 }, { nom: "Grande-Synthe", km: 3.5 }, { nom: "Coudekerque-Branche", km: 3.9 }, { nom: "Armbouts-Cappel", km: 4.0 }],
        zip: "59140",
        tier: 'HUB',
        insee: "59183",
        epci: "CU de Dunkerque",
        population: 86263,
        deptCode: "59", deptName: "Nord",
        regionName: "Hauts-de-France",
    },
    {
        slug: "aubervilliers",
        name: "Aubervilliers",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9128, lng: 2.3886 },
        price_start: 90,
        top_places: ["Pantin", "La Courneuve", "Saint-Denis", "Le Pré-Saint-Gervais"],
        zones: [{ nom: "Pantin", km: 2.0 }, { nom: "La Courneuve", km: 2.5 }, { nom: "Saint-Denis", km: 3.2 }, { nom: "Le Pré-Saint-Gervais", km: 3.4 }],
        zip: "93300",
        tier: 'HUB',
        insee: "93001",
        epci: "Métropole du Grand Paris",
        population: 88365,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "versailles",
        name: "Versailles",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8039, lng: 2.1191 },
        price_start: 90,
        top_places: ["Le Chesnay-Rocquencourt", "Buc", "Viroflay", "Saint-Cyr-l'École"],
        zones: [{ nom: "Le Chesnay-Rocquencourt", km: 2.7 }, { nom: "Buc", km: 3.4 }, { nom: "Viroflay", km: 3.9 }, { nom: "Saint-Cyr-l'École", km: 3.9 }],
        zip: "78000",
        tier: 'HUB',
        insee: "78646",
        epci: "CA Versailles Grand Parc (CAVGP)",
        population: 84095,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "colombes",
        name: "Colombes",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9218, lng: 2.2469 },
        price_start: 90,
        top_places: ["La Garenne-Colombes", "Bois-Colombes", "Bezons", "Courbevoie"],
        zones: [{ nom: "La Garenne-Colombes", km: 1.7 }, { nom: "Bois-Colombes", km: 1.8 }, { nom: "Bezons", km: 2.4 }, { nom: "Courbevoie", km: 2.8 }],
        zip: "92700",
        tier: 'HUB',
        insee: "92025",
        epci: "Métropole du Grand Paris",
        population: 91053,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "asnieres-sur-seine",
        name: "Asnières-sur-Seine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9181, lng: 2.2935 },
        price_start: 90,
        top_places: ["Gennevilliers", "Clichy", "Bois-Colombes", "Levallois-Perret"],
        zones: [{ nom: "Gennevilliers", km: 1.6 }, { nom: "Clichy", km: 1.7 }, { nom: "Bois-Colombes", km: 1.8 }, { nom: "Levallois-Perret", km: 2.7 }],
        zip: "92600",
        tier: 'HUB',
        insee: "92004",
        epci: "Métropole du Grand Paris",
        population: 93941,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "aulnay-sous-bois",
        name: "Aulnay-sous-Bois",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9457, lng: 2.4918 },
        price_start: 90,
        top_places: ["Le Blanc-Mesnil", "Sevran", "Villepinte", "Drancy"],
        zones: [{ nom: "Le Blanc-Mesnil", km: 2.7 }, { nom: "Sevran", km: 3.0 }, { nom: "Villepinte", km: 3.2 }, { nom: "Drancy", km: 4.1 }],
        zip: "93600",
        tier: 'HUB',
        insee: "93005",
        epci: "Métropole du Grand Paris",
        population: 87599,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "courbevoie",
        name: "Courbevoie",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8976, lng: 2.2574 },
        price_start: 90,
        top_places: ["Neuilly-sur-Seine", "La Garenne-Colombes", "Bois-Colombes", "Puteaux"],
        zones: [{ nom: "Neuilly-sur-Seine", km: 1.4 }, { nom: "La Garenne-Colombes", km: 1.5 }, { nom: "Bois-Colombes", km: 2.1 }, { nom: "Puteaux", km: 2.2 }],
        zip: "92400",
        tier: 'HUB',
        insee: "92026",
        epci: "Métropole du Grand Paris",
        population: 82902,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "rueil-malmaison",
        name: "Rueil-Malmaison",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8717, lng: 2.1806 },
        price_start: 90,
        top_places: ["Suresnes", "Garches", "Bougival", "Nanterre"],
        zones: [{ nom: "Suresnes", km: 2.8 }, { nom: "Garches", km: 2.8 }, { nom: "Bougival", km: 3.2 }, { nom: "Nanterre", km: 3.3 }],
        zip: "92500",
        tier: 'HUB',
        insee: "92063",
        epci: "Métropole du Grand Paris",
        population: 82874,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "champigny-sur-marne",
        name: "Champigny-sur-Marne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8173, lng: 2.5206 },
        price_start: 90,
        top_places: ["Villiers-sur-Marne", "Bry-sur-Marne", "Saint-Maur-des-Fossés", "Chennevières-sur-Marne"],
        zones: [{ nom: "Villiers-sur-Marne", km: 2.3 }, { nom: "Bry-sur-Marne", km: 2.4 }, { nom: "Saint-Maur-des-Fossés", km: 2.8 }, { nom: "Chennevières-sur-Marne", km: 3.0 }],
        zip: "94500",
        tier: 'HUB',
        insee: "94017",
        epci: "Métropole du Grand Paris",
        population: 78072,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-maur-des-fosses",
        name: "Saint-Maur-des-Fossés",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7999, lng: 2.4921 },
        price_start: 90,
        top_places: ["Joinville-le-Pont", "Champigny-sur-Marne", "Bonneuil-sur-Marne", "Créteil"],
        zones: [{ nom: "Joinville-le-Pont", km: 2.8 }, { nom: "Champigny-sur-Marne", km: 2.8 }, { nom: "Bonneuil-sur-Marne", km: 3.1 }, { nom: "Créteil", km: 3.4 }],
        zip: "94100",
        tier: 'HUB',
        insee: "94068",
        epci: "Métropole du Grand Paris",
        population: 76572,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "la-rochelle",
        name: "La Rochelle",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.162, lng: -1.1765 },
        price_start: 90,
        top_places: ["Lagord", "L'Houmeau", "Nieul-sur-Mer", "Puilboreau"],
        zones: [{ nom: "Lagord", km: 3.2 }, { nom: "L'Houmeau", km: 3.6 }, { nom: "Nieul-sur-Mer", km: 5.4 }, { nom: "Puilboreau", km: 5.4 }],
        zip: "17000",
        tier: 'HUB',
        insee: "17300",
        epci: "CA de La Rochelle",
        population: 79851,
        deptCode: "17", deptName: "Charente-Maritime",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "calais",
        name: "Calais",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 50.9523, lng: 1.869 },
        price_start: 90,
        top_places: ["Coquelles", "Coulogne", "Marck", "Fréthun"],
        zones: [{ nom: "Coquelles", km: 4.2 }, { nom: "Coulogne", km: 4.7 }, { nom: "Marck", km: 5.8 }, { nom: "Fréthun", km: 5.8 }],
        zip: "62100",
        tier: 'HUB',
        insee: "62193",
        epci: "CA Grand Calais Terres et Mers",
        population: 67571,
        deptCode: "62", deptName: "Pas-de-Calais",
        regionName: "Hauts-de-France",
    },
    {
        slug: "beziers",
        name: "Béziers",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 43.3481, lng: 3.2342 },
        price_start: 90,
        top_places: ["Boujan-sur-Libron", "Villeneuve-lès-Béziers", "Lignan-sur-Orb", "Sauvian"],
        zones: [{ nom: "Boujan-sur-Libron", km: 4.3 }, { nom: "Villeneuve-lès-Béziers", km: 5.7 }, { nom: "Lignan-sur-Orb", km: 6.3 }, { nom: "Sauvian", km: 6.8 }],
        zip: "34500",
        tier: 'HUB',
        insee: "34032",
        epci: "CA de Béziers-Méditerranée",
        population: 81545,
        deptCode: "34", deptName: "Hérault",
        regionName: "Occitanie",
    },
    {
        slug: "colmar",
        name: "Colmar",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.1115, lng: 7.3924 },
        price_start: 90,
        top_places: ["Porte du Ried", "Houssen", "Horbourg-Wihr", "Wickerschwihr"],
        zones: [{ nom: "Porte du Ried", km: 2.8 }, { nom: "Houssen", km: 3.0 }, { nom: "Horbourg-Wihr", km: 3.4 }, { nom: "Wickerschwihr", km: 3.4 }],
        zip: "68000",
        tier: 'HUB',
        insee: "68066",
        epci: "CA Colmar Agglomération",
        population: 66970,
        deptCode: "68", deptName: "Haut-Rhin",
        regionName: "Grand Est",
    },
    {
        slug: "bourges",
        name: "Bourges",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.078, lng: 2.3983 },
        price_start: 90,
        top_places: ["Saint-Doulchard", "Trouy", "La Chapelle-Saint-Ursin", "Saint-Germain-du-Puy"],
        zones: [{ nom: "Saint-Doulchard", km: 5.0 }, { nom: "Trouy", km: 6.3 }, { nom: "La Chapelle-Saint-Ursin", km: 6.4 }, { nom: "Saint-Germain-du-Puy", km: 7.3 }],
        zip: "18000",
        tier: 'HUB',
        insee: "18033",
        epci: "CA Bourges Plus",
        population: 64186,
        deptCode: "18", deptName: "Cher",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "quimper",
        name: "Quimper",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.9982, lng: -4.0972 },
        price_start: 90,
        top_places: ["Ergué-Gabéric", "Pluguffan", "Saint-Évarzec", "Plonéis"],
        zones: [{ nom: "Ergué-Gabéric", km: 6.6 }, { nom: "Pluguffan", km: 7.3 }, { nom: "Saint-Évarzec", km: 7.9 }, { nom: "Plonéis", km: 8.2 }],
        zip: "29000",
        tier: 'HUB',
        insee: "29232",
        epci: "CA Quimper Bretagne Occidentale",
        population: 64385,
        deptCode: "29", deptName: "Finistère",
        regionName: "Bretagne",
    },
    {
        slug: "valence",
        name: "Valence",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 44.9234, lng: 4.9164 },
        price_start: 90,
        top_places: ["Malissard", "Bourg-lès-Valence", "Portes-lès-Valence", "Beaumont-lès-Valence"],
        zones: [{ nom: "Malissard", km: 4.2 }, { nom: "Bourg-lès-Valence", km: 4.9 }, { nom: "Portes-lès-Valence", km: 6.0 }, { nom: "Beaumont-lès-Valence", km: 6.0 }],
        zip: "26000",
        tier: 'HUB',
        insee: "26362",
        epci: "CA Valence Romans Agglo",
        population: 64458,
        deptCode: "26", deptName: "Drôme",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "ajaccio",
        name: "Ajaccio",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 41.9228, lng: 8.7058 },
        price_start: 90,
        top_places: ["Alata", "Villanova", "Appietto", "Afa"],
        zones: [{ nom: "Alata", km: 5.6 }, { nom: "Villanova", km: 5.9 }, { nom: "Appietto", km: 8.5 }, { nom: "Afa", km: 10.0 }],
        zip: "20000",
        tier: 'HUB',
        insee: "2A004",
        epci: "CA du Pays Ajaccien",
        population: 76320,
        deptCode: "2A", deptName: "Corse-du-Sud",
        regionName: "Corse",
    },
    {
        slug: "bastia",
        name: "Bastia",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 42.6861, lng: 9.424 },
        price_start: 90,
        top_places: ["Ville-di-Pietrabugno", "Furiani", "Barbaggio", "San-Martino-di-Lota"],
        zones: [{ nom: "Ville-di-Pietrabugno", km: 3.4 }, { nom: "Furiani", km: 3.5 }, { nom: "Barbaggio", km: 5.0 }, { nom: "San-Martino-di-Lota", km: 5.0 }],
        zip: "20200",
        tier: 'HUB',
        insee: "2B033",
        epci: "CA de Bastia",
        population: 46867,
        deptCode: "2B", deptName: "Haute-Corse",
        regionName: "Corse",
    },
    {
        slug: "chambery",
        name: "Chambéry",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.5822, lng: 5.9064 },
        price_start: 90,
        top_places: ["Bassens", "Cognin", "Jacob-Bellecombette", "Barberaz"],
        zones: [{ nom: "Bassens", km: 2.5 }, { nom: "Cognin", km: 2.7 }, { nom: "Jacob-Bellecombette", km: 3.5 }, { nom: "Barberaz", km: 4.1 }],
        zip: "73000",
        tier: 'HUB',
        insee: "73065",
        epci: "CA du Grand Chambéry",
        population: 59964,
        deptCode: "73", deptName: "Savoie",
        regionName: "Auvergne-Rhône-Alpes",
    },
    {
        slug: "niort",
        name: "Niort",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.3274, lng: -0.4613 },
        price_start: 90,
        top_places: ["Sciecq", "Bessines", "Aiffres", "Chauray"],
        zones: [{ nom: "Sciecq", km: 4.8 }, { nom: "Bessines", km: 5.8 }, { nom: "Aiffres", km: 6.1 }, { nom: "Chauray", km: 6.5 }],
        zip: "79000",
        tier: 'HUB',
        insee: "79191",
        epci: "CA du Niortais",
        population: 59854,
        deptCode: "79", deptName: "Deux-Sèvres",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "lorient",
        name: "Lorient",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.7494, lng: -3.3799 },
        price_start: 90,
        top_places: ["Larmor-Plage", "Locmiquélic", "Lanester", "Port-Louis"],
        zones: [{ nom: "Larmor-Plage", km: 3.8 }, { nom: "Locmiquélic", km: 4.6 }, { nom: "Lanester", km: 4.6 }, { nom: "Port-Louis", km: 5.0 }],
        zip: "56100",
        tier: 'HUB',
        insee: "56121",
        epci: "CA Lorient Agglomération",
        population: 58329,
        deptCode: "56", deptName: "Morbihan",
        regionName: "Bretagne",
    },
    {
        slug: "troyes",
        name: "Troyes",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.2924, lng: 4.0761 },
        price_start: 90,
        top_places: ["Saint-André-les-Vergers", "Saint-Julien-les-Villas", "Les Noës-près-Troyes", "Rosières-près-Troyes"],
        zones: [{ nom: "Saint-André-les-Vergers", km: 2.8 }, { nom: "Saint-Julien-les-Villas", km: 2.8 }, { nom: "Les Noës-près-Troyes", km: 2.9 }, { nom: "Rosières-près-Troyes", km: 3.3 }],
        zip: "10000",
        tier: 'HUB',
        insee: "10387",
        epci: "CA Troyes Champagne Métropole",
        population: 62088,
        deptCode: "10", deptName: "Aube",
        regionName: "Grand Est",
    },
    {
        slug: "levallois-perret",
        name: "Levallois-Perret",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8946, lng: 2.2874 },
        price_start: 90,
        top_places: ["Clichy", "Neuilly-sur-Seine", "Courbevoie", "Asnières-sur-Seine"],
        zones: [{ nom: "Clichy", km: 1.6 }, { nom: "Neuilly-sur-Seine", km: 1.9 }, { nom: "Courbevoie", km: 2.2 }, { nom: "Asnières-sur-Seine", km: 2.7 }],
        zip: "92300",
        tier: 'HUB',
        insee: "92044",
        epci: "Métropole du Grand Paris",
        population: 68092,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "issy-les-moulineaux",
        name: "Issy-les-Moulineaux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.824, lng: 2.2628 },
        price_start: 90,
        top_places: ["Vanves", "Boulogne-Billancourt", "Malakoff", "Châtillon"],
        zones: [{ nom: "Vanves", km: 1.8 }, { nom: "Boulogne-Billancourt", km: 2.1 }, { nom: "Malakoff", km: 2.4 }, { nom: "Châtillon", km: 3.0 }],
        zip: "92130",
        tier: 'HUB',
        insee: "92040",
        epci: "Métropole du Grand Paris",
        population: 67669,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "boulogne-billancourt",
        name: "Boulogne-Billancourt",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8375, lng: 2.2429 },
        price_start: 90,
        top_places: ["Issy-les-Moulineaux", "Saint-Cloud", "Sèvres", "Vanves"],
        zones: [{ nom: "Issy-les-Moulineaux", km: 2.1 }, { nom: "Saint-Cloud", km: 3.0 }, { nom: "Sèvres", km: 3.2 }, { nom: "Vanves", km: 3.7 }],
        zip: "92100",
        tier: 'HUB',
        insee: "92012",
        epci: "Métropole du Grand Paris",
        population: 119019,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-denis",
        name: "Saint-Denis",
        heroTitle: "Sécurité Incendie",
        geo: { lat: -20.9434, lng: 55.4444 },
        price_start: 90,
        top_places: ["La Possession", "Sainte-Marie", "Salazie", "Le Port"],
        zones: [{ nom: "La Possession", km: 8.0 }, { nom: "Sainte-Marie", km: 8.2 }, { nom: "Salazie", km: 14.1 }, { nom: "Le Port", km: 14.6 }],
        zip: "97400",
        tier: 'HUB',
        insee: "97411",
        epci: "CA Intercommunale du Nord de la Réunion (CINOR)",
        population: 155634,
        deptCode: "974", deptName: "La Réunion",
        regionName: "La Réunion",
    },
    {
        slug: "cergy",
        name: "Cergy",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.0373, lng: 2.0455 },
        price_start: 90,
        top_places: ["Vauréal", "Neuville-sur-Oise", "Jouy-le-Moutier", "Courdimanche"],
        zones: [{ nom: "Vauréal", km: 1.7 }, { nom: "Neuville-sur-Oise", km: 2.4 }, { nom: "Jouy-le-Moutier", km: 2.9 }, { nom: "Courdimanche", km: 3.4 }],
        zip: "95000",
        tier: 'HUB',
        insee: "95127",
        epci: "CA de Cergy-Pontoise",
        population: 70906,
        deptCode: "95", deptName: "Val-d'Oise",
        regionName: "Île-de-France",
    },
    {
        slug: "evry-courcouronnes",
        name: "Évry-Courcouronnes",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.6287, lng: 2.4313 },
        price_start: 90,
        top_places: ["Ris-Orangis", "Lisses", "Bondoufle", "Corbeil-Essonnes"],
        zones: [{ nom: "Ris-Orangis", km: 2.4 }, { nom: "Lisses", km: 3.9 }, { nom: "Bondoufle", km: 4.1 }, { nom: "Corbeil-Essonnes", km: 4.3 }],
        zip: "91000",
        tier: 'HUB',
        insee: "91228",
        epci: "CA Grand Paris Sud Seine Essonne Sénart",
        population: 66919,
        deptCode: "91", deptName: "Essonne",
        regionName: "Île-de-France",
    },
    {
        slug: "massy",
        name: "Massy",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7263, lng: 2.2696 },
        price_start: 90,
        top_places: ["Champlan", "Verrières-le-Buisson", "Palaiseau", "Antony"],
        zones: [{ nom: "Champlan", km: 2.1 }, { nom: "Verrières-le-Buisson", km: 3.0 }, { nom: "Palaiseau", km: 3.2 }, { nom: "Antony", km: 3.4 }],
        zip: "91300",
        tier: 'HUB',
        insee: "91377",
        epci: "CA Communauté Paris-Saclay",
        population: 51729,
        deptCode: "91", deptName: "Essonne",
        regionName: "Île-de-France",
    },
    {
        slug: "palaiseau",
        name: "Palaiseau",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7155, lng: 2.2293 },
        price_start: 90,
        top_places: ["Villebon-sur-Yvette", "Igny", "Vauhallan", "Massy"],
        zones: [{ nom: "Villebon-sur-Yvette", km: 2.2 }, { nom: "Igny", km: 2.5 }, { nom: "Vauhallan", km: 2.7 }, { nom: "Massy", km: 3.2 }],
        zip: "91120",
        tier: 'HUB',
        insee: "91477",
        epci: "CA Communauté Paris-Saclay",
        population: 37471,
        deptCode: "91", deptName: "Essonne",
        regionName: "Île-de-France",
    },
    {
        slug: "sarcelles",
        name: "Sarcelles",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9925, lng: 2.3858 },
        price_start: 90,
        top_places: ["Villiers-le-Bel", "Arnouville", "Groslay", "Garges-lès-Gonesse"],
        zones: [{ nom: "Villiers-le-Bel", km: 2.2 }, { nom: "Arnouville", km: 2.4 }, { nom: "Groslay", km: 2.6 }, { nom: "Garges-lès-Gonesse", km: 2.9 }],
        zip: "95200",
        tier: 'HUB',
        insee: "95585",
        epci: "CA Roissy Pays de France",
        population: 59173,
        deptCode: "95", deptName: "Val-d'Oise",
        regionName: "Île-de-France",
    },
    {
        slug: "meaux",
        name: "Meaux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9573, lng: 2.9035 },
        price_start: 90,
        top_places: ["Poincy", "Nanteuil-lès-Meaux", "Crégy-lès-Meaux", "Fublaines"],
        zones: [{ nom: "Poincy", km: 2.4 }, { nom: "Nanteuil-lès-Meaux", km: 2.8 }, { nom: "Crégy-lès-Meaux", km: 3.0 }, { nom: "Fublaines", km: 3.6 }],
        zip: "77100",
        tier: 'HUB',
        insee: "77284",
        epci: "CA du Pays de Meaux",
        population: 56905,
        deptCode: "77", deptName: "Seine-et-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "chelles",
        name: "Chelles",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8845, lng: 2.5954 },
        price_start: 90,
        top_places: ["Montfermeil", "Gournay-sur-Marne", "Vaires-sur-Marne", "Brou-sur-Chantereine"],
        zones: [{ nom: "Montfermeil", km: 2.5 }, { nom: "Gournay-sur-Marne", km: 3.0 }, { nom: "Vaires-sur-Marne", km: 3.2 }, { nom: "Brou-sur-Chantereine", km: 3.3 }],
        zip: "77500",
        tier: 'HUB',
        insee: "77108",
        epci: "CA Paris - Vallée de la Marne",
        population: 54620,
        deptCode: "77", deptName: "Seine-et-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "noisy-le-grand",
        name: "Noisy-le-Grand",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8327, lng: 2.556 },
        price_start: 90,
        top_places: ["Villiers-sur-Marne", "Bry-sur-Marne", "Champigny-sur-Marne", "Le Plessis-Trévise"],
        zones: [{ nom: "Villiers-sur-Marne", km: 0.8 }, { nom: "Bry-sur-Marne", km: 2.6 }, { nom: "Champigny-sur-Marne", km: 3.1 }, { nom: "Le Plessis-Trévise", km: 3.1 }],
        zip: "93160",
        tier: 'HUB',
        insee: "93051",
        epci: "Métropole du Grand Paris",
        population: 72978,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "fontenay-sous-bois",
        name: "Fontenay-sous-Bois",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8503, lng: 2.4736 },
        price_start: 90,
        top_places: ["Nogent-sur-Marne", "Montreuil", "Le Perreux-sur-Marne", "Vincennes"],
        zones: [{ nom: "Nogent-sur-Marne", km: 1.6 }, { nom: "Montreuil", km: 2.3 }, { nom: "Le Perreux-sur-Marne", km: 2.4 }, { nom: "Vincennes", km: 2.6 }],
        zip: "94120",
        tier: 'HUB',
        insee: "94033",
        epci: "Métropole du Grand Paris",
        population: 53757,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "vincennes",
        name: "Vincennes",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8471, lng: 2.4383 },
        price_start: 90,
        top_places: ["Saint-Mandé", "Montreuil", "Bagnolet", "Fontenay-sous-Bois"],
        zones: [{ nom: "Saint-Mandé", km: 1.5 }, { nom: "Montreuil", km: 2.0 }, { nom: "Bagnolet", km: 2.4 }, { nom: "Fontenay-sous-Bois", km: 2.6 }],
        zip: "94300",
        tier: 'HUB',
        insee: "94080",
        epci: "Métropole du Grand Paris",
        population: 48193,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "le-blanc-mesnil",
        name: "Le Blanc-Mesnil",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9372, lng: 2.4576 },
        price_start: 90,
        top_places: ["Drancy", "Le Bourget", "Aulnay-sous-Bois", "Dugny"],
        zones: [{ nom: "Drancy", km: 1.7 }, { nom: "Le Bourget", km: 2.1 }, { nom: "Aulnay-sous-Bois", km: 2.7 }, { nom: "Dugny", km: 2.7 }],
        zip: "93150",
        tier: 'HUB',
        insee: "93007",
        epci: "Métropole du Grand Paris",
        population: 62376,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "bondy",
        name: "Bondy",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9036, lng: 2.4846 },
        price_start: 90,
        top_places: ["Les Pavillons-sous-Bois", "Noisy-le-Sec", "Villemomble", "Le Raincy"],
        zones: [{ nom: "Les Pavillons-sous-Bois", km: 1.6 }, { nom: "Noisy-le-Sec", km: 2.4 }, { nom: "Villemomble", km: 2.6 }, { nom: "Le Raincy", km: 2.7 }],
        zip: "93140",
        tier: 'HUB',
        insee: "93010",
        epci: "Métropole du Grand Paris",
        population: 50595,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "epinay-sur-seine",
        name: "Épinay-sur-Seine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9544, lng: 2.3172 },
        price_start: 90,
        top_places: ["L'Île-Saint-Denis", "Deuil-la-Barre", "Villetaneuse", "Enghien-les-Bains"],
        zones: [{ nom: "L'Île-Saint-Denis", km: 0.9 }, { nom: "Deuil-la-Barre", km: 1.9 }, { nom: "Villetaneuse", km: 2.0 }, { nom: "Enghien-les-Bains", km: 2.0 }],
        zip: "93800",
        tier: 'HUB',
        insee: "93031",
        epci: "Métropole du Grand Paris",
        population: 52833,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "sevran",
        name: "Sevran",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9378, lng: 2.5311 },
        price_start: 90,
        top_places: ["Villepinte", "Livry-Gargan", "Aulnay-sous-Bois", "Clichy-sous-Bois"],
        zones: [{ nom: "Villepinte", km: 2.0 }, { nom: "Livry-Gargan", km: 2.2 }, { nom: "Aulnay-sous-Bois", km: 3.0 }, { nom: "Clichy-sous-Bois", km: 3.4 }],
        zip: "93270",
        tier: 'HUB',
        insee: "93071",
        epci: "Métropole du Grand Paris",
        population: 52535,
        deptCode: "93", deptName: "Seine-Saint-Denis",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-germain-en-laye",
        name: "Saint-Germain-en-Laye",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.931, lng: 2.1052 },
        price_start: 90,
        top_places: ["Le Mesnil-le-Roi", "Montesson", "Maisons-Laffitte", "Le Pecq"],
        zones: [{ nom: "Le Mesnil-le-Roi", km: 1.5 }, { nom: "Montesson", km: 2.7 }, { nom: "Maisons-Laffitte", km: 4.1 }, { nom: "Le Pecq", km: 4.3 }],
        zip: "78100",
        tier: 'HUB',
        insee: "78551",
        epci: "CA Saint Germain Boucles de Seine",
        population: 45931,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "mantes-la-jolie",
        name: "Mantes-la-Jolie",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9961, lng: 1.6918 },
        price_start: 90,
        top_places: ["Buchelay", "Mantes-la-Ville", "Magnanville", "Limay"],
        zones: [{ nom: "Buchelay", km: 1.7 }, { nom: "Mantes-la-Ville", km: 2.7 }, { nom: "Magnanville", km: 3.1 }, { nom: "Limay", km: 3.3 }],
        zip: "78200",
        tier: 'HUB',
        insee: "78361",
        epci: "CU Grand Paris Seine et Oise",
        population: 43526,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "poissy",
        name: "Poissy",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9241, lng: 2.025 },
        price_start: 90,
        top_places: ["Villennes-sur-Seine", "Carrières-sous-Poissy", "Aigremont", "Chambourcy"],
        zones: [{ nom: "Villennes-sur-Seine", km: 2.5 }, { nom: "Carrières-sous-Poissy", km: 2.5 }, { nom: "Aigremont", km: 2.5 }, { nom: "Chambourcy", km: 3.0 }],
        zip: "78300",
        tier: 'HUB',
        insee: "78498",
        epci: "CU Grand Paris Seine et Oise",
        population: 40983,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "sartrouville",
        name: "Sartrouville",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9374, lng: 2.1744 },
        price_start: 90,
        top_places: ["Houilles", "Maisons-Laffitte", "Carrières-sur-Seine", "Bezons"],
        zones: [{ nom: "Houilles", km: 1.5 }, { nom: "Maisons-Laffitte", km: 2.1 }, { nom: "Carrières-sur-Seine", km: 2.8 }, { nom: "Bezons", km: 3.3 }],
        zip: "78500",
        tier: 'HUB',
        insee: "78586",
        epci: "CA Saint Germain Boucles de Seine",
        population: 52763,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "houilles",
        name: "Houilles",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9266, lng: 2.1866 },
        price_start: 90,
        top_places: ["Sartrouville", "Carrières-sur-Seine", "Bezons", "Nanterre"],
        zones: [{ nom: "Sartrouville", km: 1.5 }, { nom: "Carrières-sur-Seine", km: 1.6 }, { nom: "Bezons", km: 2.1 }, { nom: "Nanterre", km: 3.4 }],
        zip: "78800",
        tier: 'HUB',
        insee: "78311",
        epci: "CA Saint Germain Boucles de Seine",
        population: 33983,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "chatou",
        name: "Chatou",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8964, lng: 2.1502 },
        price_start: 90,
        top_places: ["Le Vésinet", "Croissy-sur-Seine", "Montesson", "Carrières-sur-Seine"],
        zones: [{ nom: "Le Vésinet", km: 1.4 }, { nom: "Croissy-sur-Seine", km: 2.1 }, { nom: "Montesson", km: 2.7 }, { nom: "Carrières-sur-Seine", km: 2.9 }],
        zip: "78400",
        tier: 'HUB',
        insee: "78146",
        epci: "CA Saint Germain Boucles de Seine",
        population: 30598,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "le-vesinet",
        name: "Le Vésinet",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8928, lng: 2.1312 },
        price_start: 90,
        top_places: ["Croissy-sur-Seine", "Chatou", "Le Port-Marly", "Le Pecq"],
        zones: [{ nom: "Croissy-sur-Seine", km: 1.4 }, { nom: "Chatou", km: 1.4 }, { nom: "Le Port-Marly", km: 2.0 }, { nom: "Le Pecq", km: 2.1 }],
        zip: "78110",
        tier: 'HUB',
        insee: "78650",
        epci: "CA Saint Germain Boucles de Seine",
        population: 15554,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "croissy-sur-seine",
        name: "Croissy-sur-Seine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8805, lng: 2.1342 },
        price_start: 90,
        top_places: ["Le Vésinet", "Le Port-Marly", "Bougival", "Chatou"],
        zones: [{ nom: "Le Vésinet", km: 1.4 }, { nom: "Le Port-Marly", km: 1.7 }, { nom: "Bougival", km: 2.0 }, { nom: "Chatou", km: 2.1 }],
        zip: "78290",
        tier: 'HUB',
        insee: "78190",
        epci: "CA Saint Germain Boucles de Seine",
        population: 11013,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-cloud",
        name: "Saint-Cloud",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.844, lng: 2.2032 },
        price_start: 90,
        top_places: ["Garches", "Sèvres", "Boulogne-Billancourt", "Vaucresson"],
        zones: [{ nom: "Garches", km: 1.3 }, { nom: "Sèvres", km: 2.4 }, { nom: "Boulogne-Billancourt", km: 3.0 }, { nom: "Vaucresson", km: 3.0 }],
        zip: "92210",
        tier: 'HUB',
        insee: "92064",
        epci: "Métropole du Grand Paris",
        population: 29855,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "sevres",
        name: "Sèvres",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8223, lng: 2.2056 },
        price_start: 90,
        top_places: ["Chaville", "Ville-d'Avray", "Saint-Cloud", "Meudon"],
        zones: [{ nom: "Chaville", km: 1.8 }, { nom: "Ville-d'Avray", km: 2.2 }, { nom: "Saint-Cloud", km: 2.4 }, { nom: "Meudon", km: 2.8 }],
        zip: "92310",
        tier: 'HUB',
        insee: "92072",
        epci: "Métropole du Grand Paris",
        population: 22303,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "ville-davray",
        name: "Ville-d'Avray",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8215, lng: 2.1759 },
        price_start: 90,
        top_places: ["Marnes-la-Coquette", "Chaville", "Vaucresson", "Sèvres"],
        zones: [{ nom: "Marnes-la-Coquette", km: 0.9 }, { nom: "Chaville", km: 1.8 }, { nom: "Vaucresson", km: 2.0 }, { nom: "Sèvres", km: 2.2 }],
        zip: "92410",
        tier: 'HUB',
        insee: "92077",
        epci: "Métropole du Grand Paris",
        population: 11089,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "chaville",
        name: "Chaville",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8091, lng: 2.191 },
        price_start: 90,
        top_places: ["Viroflay", "Ville-d'Avray", "Sèvres", "Marnes-la-Coquette"],
        zones: [{ nom: "Viroflay", km: 1.6 }, { nom: "Ville-d'Avray", km: 1.8 }, { nom: "Sèvres", km: 1.8 }, { nom: "Marnes-la-Coquette", km: 2.7 }],
        zip: "92370",
        tier: 'HUB',
        insee: "92022",
        epci: "Métropole du Grand Paris",
        population: 20594,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "garches",
        name: "Garches",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8469, lng: 2.1861 },
        price_start: 90,
        top_places: ["Saint-Cloud", "Vaucresson", "Marnes-la-Coquette", "Rueil-Malmaison"],
        zones: [{ nom: "Saint-Cloud", km: 1.3 }, { nom: "Vaucresson", km: 2.0 }, { nom: "Marnes-la-Coquette", km: 2.4 }, { nom: "Rueil-Malmaison", km: 2.8 }],
        zip: "92380",
        tier: 'HUB',
        insee: "92033",
        epci: "Métropole du Grand Paris",
        population: 17743,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "vaucresson",
        name: "Vaucresson",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8377, lng: 2.1628 },
        price_start: 90,
        top_places: ["Marnes-la-Coquette", "Garches", "Ville-d'Avray", "La Celle-Saint-Cloud"],
        zones: [{ nom: "Marnes-la-Coquette", km: 1.1 }, { nom: "Garches", km: 2.0 }, { nom: "Ville-d'Avray", km: 2.0 }, { nom: "La Celle-Saint-Cloud", km: 2.5 }],
        zip: "92420",
        tier: 'HUB',
        insee: "92076",
        epci: "Métropole du Grand Paris",
        population: 8432,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "marnes-la-coquette",
        name: "Marnes-la-Coquette",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8286, lng: 2.1689 },
        price_start: 90,
        top_places: ["Ville-d'Avray", "Vaucresson", "Garches", "Chaville"],
        zones: [{ nom: "Ville-d'Avray", km: 0.9 }, { nom: "Vaucresson", km: 1.1 }, { nom: "Garches", km: 2.4 }, { nom: "Chaville", km: 2.7 }],
        zip: "92430",
        tier: 'HUB',
        insee: "92047",
        epci: "Métropole du Grand Paris",
        population: 1752,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-nom-la-breteche",
        name: "Saint-Nom-la-Bretèche",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8621, lng: 2.0168 },
        price_start: 90,
        top_places: ["Chavenay", "Feucherolles", "L'Étang-la-Ville", "Noisy-le-Roi"],
        zones: [{ nom: "Chavenay", km: 2.8 }, { nom: "Feucherolles", km: 3.0 }, { nom: "L'Étang-la-Ville", km: 3.1 }, { nom: "Noisy-le-Roi", km: 3.2 }],
        zip: "78860",
        tier: 'HUB',
        insee: "78571",
        epci: "CC Gally Mauldre",
        population: 4965,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "maisons-laffitte",
        name: "Maisons-Laffitte",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.9503, lng: 2.1533 },
        price_start: 90,
        top_places: ["Sartrouville", "La Frette-sur-Seine", "Le Mesnil-le-Roi", "Houilles"],
        zones: [{ nom: "Sartrouville", km: 2.1 }, { nom: "La Frette-sur-Seine", km: 3.0 }, { nom: "Le Mesnil-le-Roi", km: 3.6 }, { nom: "Houilles", km: 3.6 }],
        zip: "78600",
        tier: 'HUB',
        insee: "78358",
        epci: "CA Saint Germain Boucles de Seine",
        population: 23093,
        deptCode: "78", deptName: "Yvelines",
        regionName: "Île-de-France",
    },
    {
        slug: "antony",
        name: "Antony",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7507, lng: 2.2976 },
        price_start: 90,
        top_places: ["Fresnes", "Sceaux", "Wissous", "Verrières-le-Buisson"],
        zones: [{ nom: "Fresnes", km: 2.2 }, { nom: "Sceaux", km: 2.8 }, { nom: "Wissous", km: 3.1 }, { nom: "Verrières-le-Buisson", km: 3.2 }],
        zip: "92160",
        tier: 'HUB',
        insee: "92002",
        epci: "Métropole du Grand Paris",
        population: 64263,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "clamart",
        name: "Clamart",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7957, lng: 2.2518 },
        price_start: 90,
        top_places: ["Le Plessis-Robinson", "Meudon", "Fontenay-aux-Roses", "Châtillon"],
        zones: [{ nom: "Le Plessis-Robinson", km: 1.7 }, { nom: "Meudon", km: 1.9 }, { nom: "Fontenay-aux-Roses", km: 2.7 }, { nom: "Châtillon", km: 2.8 }],
        zip: "92140",
        tier: 'HUB',
        insee: "92023",
        epci: "Métropole du Grand Paris",
        population: 58576,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "le-plessis-robinson",
        name: "Le Plessis-Robinson",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7815, lng: 2.2592 },
        price_start: 90,
        top_places: ["Châtenay-Malabry", "Clamart", "Fontenay-aux-Roses", "Sceaux"],
        zones: [{ nom: "Châtenay-Malabry", km: 1.3 }, { nom: "Clamart", km: 1.7 }, { nom: "Fontenay-aux-Roses", km: 2.3 }, { nom: "Sceaux", km: 2.8 }],
        zip: "92350",
        tier: 'HUB',
        insee: "92060",
        epci: "Métropole du Grand Paris",
        population: 28848,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "fontenay-aux-roses",
        name: "Fontenay-aux-Roses",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7895, lng: 2.2876 },
        price_start: 90,
        top_places: ["Châtillon", "Sceaux", "Bagneux", "Le Plessis-Robinson"],
        zones: [{ nom: "Châtillon", km: 1.5 }, { nom: "Sceaux", km: 1.6 }, { nom: "Bagneux", km: 1.8 }, { nom: "Le Plessis-Robinson", km: 2.3 }],
        zip: "92260",
        tier: 'HUB',
        insee: "92032",
        epci: "Métropole du Grand Paris",
        population: 24070,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "sceaux",
        name: "Sceaux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.776, lng: 2.2963 },
        price_start: 90,
        top_places: ["Bourg-la-Reine", "Fontenay-aux-Roses", "Bagneux", "Châtenay-Malabry"],
        zones: [{ nom: "Bourg-la-Reine", km: 1.6 }, { nom: "Fontenay-aux-Roses", km: 1.6 }, { nom: "Bagneux", km: 2.6 }, { nom: "Châtenay-Malabry", km: 2.7 }],
        zip: "92330",
        tier: 'HUB',
        insee: "92071",
        epci: "Métropole du Grand Paris",
        population: 20884,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "bourg-la-reine",
        name: "Bourg-la-Reine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7801, lng: 2.3167 },
        price_start: 90,
        top_places: ["Sceaux", "Cachan", "L'Haÿ-les-Roses", "Bagneux"],
        zones: [{ nom: "Sceaux", km: 1.6 }, { nom: "Cachan", km: 1.7 }, { nom: "L'Haÿ-les-Roses", km: 1.8 }, { nom: "Bagneux", km: 2.1 }],
        zip: "92340",
        tier: 'HUB',
        insee: "92014",
        epci: "Métropole du Grand Paris",
        population: 21019,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "bagneux",
        name: "Bagneux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.798, lng: 2.3093 },
        price_start: 90,
        top_places: ["Châtillon", "Cachan", "Fontenay-aux-Roses", "Arcueil"],
        zones: [{ nom: "Châtillon", km: 1.6 }, { nom: "Cachan", km: 1.8 }, { nom: "Fontenay-aux-Roses", km: 1.8 }, { nom: "Arcueil", km: 1.9 }],
        zip: "92220",
        tier: 'HUB',
        insee: "92007",
        epci: "Métropole du Grand Paris",
        population: 44572,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "malakoff",
        name: "Malakoff",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.817, lng: 2.2943 },
        price_start: 90,
        top_places: ["Vanves", "Châtillon", "Montrouge", "Bagneux"],
        zones: [{ nom: "Vanves", km: 0.7 }, { nom: "Châtillon", km: 1.6 }, { nom: "Montrouge", km: 1.6 }, { nom: "Bagneux", km: 2.4 }],
        zip: "92240",
        tier: 'HUB',
        insee: "92046",
        epci: "Métropole du Grand Paris",
        population: 30557,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "vanves",
        name: "Vanves",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8214, lng: 2.2869 },
        price_start: 90,
        top_places: ["Malakoff", "Issy-les-Moulineaux", "Châtillon", "Montrouge"],
        zones: [{ nom: "Malakoff", km: 0.7 }, { nom: "Issy-les-Moulineaux", km: 1.8 }, { nom: "Châtillon", km: 2.0 }, { nom: "Montrouge", km: 2.2 }],
        zip: "92170",
        tier: 'HUB',
        insee: "92075",
        epci: "Métropole du Grand Paris",
        population: 28622,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "montrouge",
        name: "Montrouge",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8159, lng: 2.3163 },
        price_start: 90,
        top_places: ["Malakoff", "Arcueil", "Gentilly", "Bagneux"],
        zones: [{ nom: "Malakoff", km: 1.6 }, { nom: "Arcueil", km: 1.7 }, { nom: "Gentilly", km: 2.0 }, { nom: "Bagneux", km: 2.1 }],
        zip: "92120",
        tier: 'HUB',
        insee: "92049",
        epci: "Métropole du Grand Paris",
        population: 46324,
        deptCode: "92", deptName: "Hauts-de-Seine",
        regionName: "Île-de-France",
    },
    {
        slug: "arcueil",
        name: "Arcueil",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8053, lng: 2.3328 },
        price_start: 90,
        top_places: ["Gentilly", "Cachan", "Montrouge", "Le Kremlin-Bicêtre"],
        zones: [{ nom: "Gentilly", km: 1.0 }, { nom: "Cachan", km: 1.5 }, { nom: "Montrouge", km: 1.7 }, { nom: "Le Kremlin-Bicêtre", km: 1.7 }],
        zip: "94110",
        tier: 'HUB',
        insee: "94003",
        epci: "Métropole du Grand Paris",
        population: 22200,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "cachan",
        name: "Cachan",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7914, lng: 2.3318 },
        price_start: 90,
        top_places: ["Arcueil", "Bourg-la-Reine", "L'Haÿ-les-Roses", "Bagneux"],
        zones: [{ nom: "Arcueil", km: 1.5 }, { nom: "Bourg-la-Reine", km: 1.7 }, { nom: "L'Haÿ-les-Roses", km: 1.7 }, { nom: "Bagneux", km: 1.8 }],
        zip: "94230",
        tier: 'HUB',
        insee: "94016",
        epci: "Métropole du Grand Paris",
        population: 31103,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "gentilly",
        name: "Gentilly",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.812, lng: 2.3426 },
        price_start: 90,
        top_places: ["Arcueil", "Le Kremlin-Bicêtre", "Montrouge", "Cachan"],
        zones: [{ nom: "Arcueil", km: 1.0 }, { nom: "Le Kremlin-Bicêtre", km: 1.0 }, { nom: "Montrouge", km: 2.0 }, { nom: "Cachan", km: 2.4 }],
        zip: "94250",
        tier: 'HUB',
        insee: "94037",
        epci: "Métropole du Grand Paris",
        population: 19963,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "le-kremlin-bicetre",
        name: "Le Kremlin-Bicêtre",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8087, lng: 2.356 },
        price_start: 90,
        top_places: ["Gentilly", "Villejuif", "Arcueil", "Ivry-sur-Seine"],
        zones: [{ nom: "Gentilly", km: 1.0 }, { nom: "Villejuif", km: 1.7 }, { nom: "Arcueil", km: 1.7 }, { nom: "Ivry-sur-Seine", km: 2.3 }],
        zip: "94270",
        tier: 'HUB',
        insee: "94043",
        epci: "Métropole du Grand Paris",
        population: 24110,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "ivry-sur-seine",
        name: "Ivry-sur-Seine",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8125, lng: 2.3872 },
        price_start: 90,
        top_places: ["Charenton-le-Pont", "Le Kremlin-Bicêtre", "Vitry-sur-Seine", "Villejuif"],
        zones: [{ nom: "Charenton-le-Pont", km: 1.7 }, { nom: "Le Kremlin-Bicêtre", km: 2.3 }, { nom: "Vitry-sur-Seine", km: 2.6 }, { nom: "Villejuif", km: 2.9 }],
        zip: "94200",
        tier: 'HUB',
        insee: "94041",
        epci: "Métropole du Grand Paris",
        population: 65064,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "villejuif",
        name: "Villejuif",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7934, lng: 2.3603 },
        price_start: 90,
        top_places: ["Le Kremlin-Bicêtre", "Cachan", "L'Haÿ-les-Roses", "Arcueil"],
        zones: [{ nom: "Le Kremlin-Bicêtre", km: 1.7 }, { nom: "Cachan", km: 2.1 }, { nom: "L'Haÿ-les-Roses", km: 2.2 }, { nom: "Arcueil", km: 2.4 }],
        zip: "94800",
        tier: 'HUB',
        insee: "94076",
        epci: "Métropole du Grand Paris",
        population: 60183,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "alfortville",
        name: "Alfortville",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7963, lng: 2.4214 },
        price_start: 90,
        top_places: ["Maisons-Alfort", "Vitry-sur-Seine", "Créteil", "Saint-Maurice"],
        zones: [{ nom: "Maisons-Alfort", km: 1.5 }, { nom: "Vitry-sur-Seine", km: 2.1 }, { nom: "Créteil", km: 2.6 }, { nom: "Saint-Maurice", km: 2.8 }],
        zip: "94140",
        tier: 'HUB',
        insee: "94002",
        epci: "Métropole du Grand Paris",
        population: 45531,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "maisons-alfort",
        name: "Maisons-Alfort",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8017, lng: 2.44 },
        price_start: 90,
        top_places: ["Alfortville", "Saint-Maurice", "Créteil", "Joinville-le-Pont"],
        zones: [{ nom: "Alfortville", km: 1.5 }, { nom: "Saint-Maurice", km: 1.8 }, { nom: "Créteil", km: 2.1 }, { nom: "Joinville-le-Pont", km: 2.9 }],
        zip: "94700",
        tier: 'HUB',
        insee: "94046",
        epci: "Métropole du Grand Paris",
        population: 56799,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "joinville-le-pont",
        name: "Joinville-le-Pont",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8199, lng: 2.4685 },
        price_start: 90,
        top_places: ["Saint-Maurice", "Nogent-sur-Marne", "Saint-Maur-des-Fossés", "Maisons-Alfort"],
        zones: [{ nom: "Saint-Maurice", km: 1.9 }, { nom: "Nogent-sur-Marne", km: 2.1 }, { nom: "Saint-Maur-des-Fossés", km: 2.8 }, { nom: "Maisons-Alfort", km: 2.9 }],
        zip: "94340",
        tier: 'HUB',
        insee: "94042",
        epci: "Métropole du Grand Paris",
        population: 20525,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "nogent-sur-marne",
        name: "Nogent-sur-Marne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.837, lng: 2.4811 },
        price_start: 90,
        top_places: ["Fontenay-sous-Bois", "Le Perreux-sur-Marne", "Joinville-le-Pont", "Bry-sur-Marne"],
        zones: [{ nom: "Fontenay-sous-Bois", km: 1.6 }, { nom: "Le Perreux-sur-Marne", km: 1.9 }, { nom: "Joinville-le-Pont", km: 2.1 }, { nom: "Bry-sur-Marne", km: 3.0 }],
        zip: "94130",
        tier: 'HUB',
        insee: "94052",
        epci: "Métropole du Grand Paris",
        population: 32455,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "le-perreux-sur-marne",
        name: "Le Perreux-sur-Marne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8433, lng: 2.5045 },
        price_start: 90,
        top_places: ["Bry-sur-Marne", "Nogent-sur-Marne", "Neuilly-Plaisance", "Fontenay-sous-Bois"],
        zones: [{ nom: "Bry-sur-Marne", km: 1.4 }, { nom: "Nogent-sur-Marne", km: 1.9 }, { nom: "Neuilly-Plaisance", km: 2.3 }, { nom: "Fontenay-sous-Bois", km: 2.4 }],
        zip: "94170",
        tier: 'HUB',
        insee: "94058",
        epci: "Métropole du Grand Paris",
        population: 35260,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "bry-sur-marne",
        name: "Bry-sur-Marne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8392, lng: 2.5224 },
        price_start: 90,
        top_places: ["Le Perreux-sur-Marne", "Villiers-sur-Marne", "Champigny-sur-Marne", "Noisy-le-Grand"],
        zones: [{ nom: "Le Perreux-sur-Marne", km: 1.4 }, { nom: "Villiers-sur-Marne", km: 2.3 }, { nom: "Champigny-sur-Marne", km: 2.4 }, { nom: "Noisy-le-Grand", km: 2.6 }],
        zip: "94360",
        tier: 'HUB',
        insee: "94015",
        epci: "Métropole du Grand Paris",
        population: 18503,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "villiers-sur-marne",
        name: "Villiers-sur-Marne",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8278, lng: 2.5482 },
        price_start: 90,
        top_places: ["Noisy-le-Grand", "Bry-sur-Marne", "Champigny-sur-Marne", "Le Plessis-Trévise"],
        zones: [{ nom: "Noisy-le-Grand", km: 0.8 }, { nom: "Bry-sur-Marne", km: 2.3 }, { nom: "Champigny-sur-Marne", km: 2.3 }, { nom: "Le Plessis-Trévise", km: 3.0 }],
        zip: "94350",
        tier: 'HUB',
        insee: "94079",
        epci: "Métropole du Grand Paris",
        population: 33162,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "saint-maurice",
        name: "Saint-Maurice",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8179, lng: 2.4423 },
        price_start: 90,
        top_places: ["Maisons-Alfort", "Joinville-le-Pont", "Charenton-le-Pont", "Alfortville"],
        zones: [{ nom: "Maisons-Alfort", km: 1.8 }, { nom: "Joinville-le-Pont", km: 1.9 }, { nom: "Charenton-le-Pont", km: 2.8 }, { nom: "Alfortville", km: 2.8 }],
        zip: "94410",
        tier: 'HUB',
        insee: "94069",
        epci: "Métropole du Grand Paris",
        population: 14506,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "charenton-le-pont",
        name: "Charenton-le-Pont",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.8229, lng: 2.405 },
        price_start: 90,
        top_places: ["Ivry-sur-Seine", "Saint-Mandé", "Saint-Maurice", "Alfortville"],
        zones: [{ nom: "Ivry-sur-Seine", km: 1.7 }, { nom: "Saint-Mandé", km: 2.3 }, { nom: "Saint-Maurice", km: 2.8 }, { nom: "Alfortville", km: 3.2 }],
        zip: "94220",
        tier: 'HUB',
        insee: "94018",
        epci: "Métropole du Grand Paris",
        population: 28830,
        deptCode: "94", deptName: "Val-de-Marne",
        regionName: "Île-de-France",
    },
    {
        slug: "la-roche-sur-yon",
        name: "La Roche-sur-Yon",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.6659, lng: -1.4162 },
        price_start: 90,
        top_places: ["Mouilleron-le-Captif", "Aubigny-Les Clouzeaux", "Nesmy", "La Ferrière"],
        zones: [{ nom: "Mouilleron-le-Captif", km: 6.3 }, { nom: "Aubigny-Les Clouzeaux", km: 7.7 }, { nom: "Nesmy", km: 8.4 }, { nom: "La Ferrière", km: 9.0 }],
        zip: "85000",
        tier: 'HUB',
        insee: "85191",
        epci: "CA La Roche-sur-Yon - Agglomération",
        population: 54849,
        deptCode: "85", deptName: "Vendée",
        regionName: "Pays de la Loire",
    },
    {
        slug: "angouleme",
        name: "Angoulême",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.6458, lng: 0.145 },
        price_start: 90,
        top_places: ["Saint-Michel", "Gond-Pontouvre", "Saint-Yrieix-sur-Charente", "Puymoyen"],
        zones: [{ nom: "Saint-Michel", km: 2.7 }, { nom: "Gond-Pontouvre", km: 4.1 }, { nom: "Saint-Yrieix-sur-Charente", km: 4.2 }, { nom: "Puymoyen", km: 4.3 }],
        zip: "16000",
        tier: 'HUB',
        insee: "16015",
        epci: "CA du Grand Angoulême",
        population: 41908,
        deptCode: "16", deptName: "Charente",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "auch",
        name: "Auch",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 43.6602, lng: 0.5673 },
        price_start: 90,
        top_places: ["Duran", "Castin", "Pavie", "Castillon-Massas"],
        zones: [{ nom: "Duran", km: 1.4 }, { nom: "Castin", km: 4.3 }, { nom: "Pavie", km: 6.3 }, { nom: "Castillon-Massas", km: 6.5 }],
        zip: "32000",
        tier: 'HUB',
        insee: "32013",
        epci: "CA Grand Auch Coeur de Gascogne",
        population: 22428,
        deptCode: "32", deptName: "Gers",
        regionName: "Occitanie",
    },
    {
        slug: "rodez",
        name: "Rodez",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 44.3591, lng: 2.5699 },
        price_start: 90,
        top_places: ["Onet-le-Château", "Olemps", "Le Monastère", "Sainte-Radegonde"],
        zones: [{ nom: "Onet-le-Château", km: 2.7 }, { nom: "Olemps", km: 2.7 }, { nom: "Le Monastère", km: 3.5 }, { nom: "Sainte-Radegonde", km: 6.0 }],
        zip: "12000",
        tier: 'HUB',
        insee: "12202",
        epci: "CA Rodez Agglomération",
        population: 23981,
        deptCode: "12", deptName: "Aveyron",
        regionName: "Occitanie",
    },
    {
        slug: "cahors",
        name: "Cahors",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 44.4565, lng: 1.439 },
        price_start: 90,
        top_places: ["Pradines", "Lamagdelaine", "Mercuès", "Douelle"],
        zones: [{ nom: "Pradines", km: 4.1 }, { nom: "Lamagdelaine", km: 5.4 }, { nom: "Mercuès", km: 5.9 }, { nom: "Douelle", km: 6.8 }],
        zip: "46000",
        tier: 'HUB',
        insee: "46042",
        epci: "CA du Grand Cahors",
        population: 20050,
        deptCode: "46", deptName: "Lot",
        regionName: "Occitanie",
    },
    {
        slug: "brive-la-gaillarde",
        name: "Brive-la-Gaillarde",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.145, lng: 1.5144 },
        price_start: 90,
        top_places: ["Ussac", "Noailles", "Lissac-sur-Couze", "Cosnac"],
        zones: [{ nom: "Ussac", km: 4.7 }, { nom: "Noailles", km: 5.1 }, { nom: "Lissac-sur-Couze", km: 5.5 }, { nom: "Cosnac", km: 5.7 }],
        zip: "19100",
        tier: 'HUB',
        insee: "19031",
        epci: "CA du Bassin de Brive",
        population: 47095,
        deptCode: "19", deptName: "Corrèze",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "tulle",
        name: "Tulle",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 45.2685, lng: 1.7663 },
        price_start: 90,
        top_places: ["Chanac-les-Mines", "Laguenne-sur-Avalouze", "Naves", "Les Angles-sur-Corrèze"],
        zones: [{ nom: "Chanac-les-Mines", km: 3.7 }, { nom: "Laguenne-sur-Avalouze", km: 3.9 }, { nom: "Naves", km: 5.0 }, { nom: "Les Angles-sur-Corrèze", km: 5.4 }],
        zip: "19000",
        tier: 'HUB',
        insee: "19272",
        epci: "CA Tulle Agglo",
        population: 13401,
        deptCode: "19", deptName: "Corrèze",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "gueret",
        name: "Guéret",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.1585, lng: 1.8705 },
        price_start: 90,
        top_places: ["Sainte-Feyre", "Saint-Léger-le-Guérétois", "Saint-Sulpice-le-Guérétois", "Savennes"],
        zones: [{ nom: "Sainte-Feyre", km: 3.0 }, { nom: "Saint-Léger-le-Guérétois", km: 4.4 }, { nom: "Saint-Sulpice-le-Guérétois", km: 5.3 }, { nom: "Savennes", km: 5.5 }],
        zip: "23000",
        tier: 'HUB',
        insee: "23096",
        epci: "CA du Grand Guéret",
        population: 12955,
        deptCode: "23", deptName: "Creuse",
        regionName: "Nouvelle-Aquitaine",
    },
    {
        slug: "chateauroux",
        name: "Châteauroux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 46.8023, lng: 1.6903 },
        price_start: 90,
        top_places: ["Déols", "Saint-Maur", "Le Poinçonnet", "Étrechet"],
        zones: [{ nom: "Déols", km: 4.2 }, { nom: "Saint-Maur", km: 5.4 }, { nom: "Le Poinçonnet", km: 6.0 }, { nom: "Étrechet", km: 7.0 }],
        zip: "36000",
        tier: 'HUB',
        insee: "36044",
        epci: "CA Châteauroux Métropole",
        population: 42963,
        deptCode: "36", deptName: "Indre",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "blois",
        name: "Blois",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 47.5813, lng: 1.3049 },
        price_start: 90,
        top_places: ["Saint-Sulpice-de-Pommeray", "Saint-Gervais-la-Forêt", "Chailles", "Villebarou"],
        zones: [{ nom: "Saint-Sulpice-de-Pommeray", km: 3.7 }, { nom: "Saint-Gervais-la-Forêt", km: 4.4 }, { nom: "Chailles", km: 4.7 }, { nom: "Villebarou", km: 5.0 }],
        zip: "41000",
        tier: 'HUB',
        insee: "41018",
        epci: "CA de Blois ''Agglopolys''",
        population: 47219,
        deptCode: "41", deptName: "Loir-et-Cher",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "chartres",
        name: "Chartres",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.4481, lng: 1.5046 },
        price_start: 90,
        top_places: ["Champhol", "Le Coudray", "Luisant", "Lucé"],
        zones: [{ nom: "Champhol", km: 2.3 }, { nom: "Le Coudray", km: 3.3 }, { nom: "Luisant", km: 3.9 }, { nom: "Lucé", km: 4.2 }],
        zip: "28000",
        tier: 'HUB',
        insee: "28085",
        epci: "CA Chartres Métropole",
        population: 38324,
        deptCode: "28", deptName: "Eure-et-Loir",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "dreux",
        name: "Dreux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 48.7482, lng: 1.3578 },
        price_start: 90,
        top_places: ["Vernouillet", "Montreuil", "Muzy", "Sainte-Gemme-Moronval"],
        zones: [{ nom: "Vernouillet", km: 3.8 }, { nom: "Montreuil", km: 3.8 }, { nom: "Muzy", km: 4.0 }, { nom: "Sainte-Gemme-Moronval", km: 4.5 }],
        zip: "28100",
        tier: 'HUB',
        insee: "28134",
        epci: "CA Agglo du Pays de Dreux",
        population: 31543,
        deptCode: "28", deptName: "Eure-et-Loir",
        regionName: "Centre-Val de Loire",
    },
    {
        slug: "evreux",
        name: "Évreux",
        heroTitle: "Sécurité Incendie",
        geo: { lat: 49.018, lng: 1.1406 },
        price_start: 90,
        top_places: ["Angerville-la-Campagne", "Parville", "Arnières-sur-Iton", "Fauville"],
        zones: [{ nom: "Angerville-la-Campagne", km: 3.6 }, { nom: "Parville", km: 3.7 }, { nom: "Arnières-sur-Iton", km: 4.0 }, { nom: "Fauville", km: 4.4 }],
        zip: "27000",
        tier: 'HUB',
        insee: "27229",
        epci: "CA Evreux Portes de Normandie",
        population: 49360,
        deptCode: "27", deptName: "Eure",
        regionName: "Normandie",
    },
];

// Helper to get a target by slug
export function getTargetBySlug(slug: string): NationalTarget | undefined {
    return NATIONAL_TARGETS.find(t => t.slug === slug);
}

// ========================================
// ADAPTER: Convert NationalTarget to CityConfig
// Uses pSEO for unique content per city
// ========================================
import { CityConfig } from "@/lib/db";
import { departementFromPostal } from "@/data/fr-departements";

export function getTargetAsCityConfig(slug: string): CityConfig | undefined {
    const target = NATIONAL_TARGETS.find(t => t.slug === slug);
    if (!target) return undefined;

    const priceDisplay = `À partir de ${target.price_start}€`;
    const priceDesc = "maintenance clé en main";

    const deptLabel = target.deptName ? ` (${target.deptName})` : ` (${target.zip})`;

    const uniqueDescription = `Maintenance du matériel incendie à ${target.name}${deptLabel} : extincteurs NF EN 3, blocs autonomes d'éclairage de sécurité, désenfumage et registre de sécurité. Intervention pour les entreprises, commerces, ERP et copropriétés.`;
    const uniqueMetaDescription = `Maintenance d'extincteurs et de BAES à ${target.name} (${target.zip}). Vérification annuelle, registre de sécurité et devis gratuit.`;

    return {
        slug: target.slug,
        city: target.name,
        name: `Expert extincteur ${target.name}`,
        domain: `expertsecuriteincendie.fr/ville/${target.slug}`,
        heroImage: target.heroImage || "/images/generated/city-street.png",

        postalCode: target.zip,
        // `department` reste le CODE (utilisé par le maillage VillesVoisines)
        department: departementFromPostal(target.zip)?.code || target.zip.substring(0, 2),
        region: target.regionName || departementFromPostal(target.zip)?.region || "France",

        description: uniqueDescription,
        geo: target.geo,

        features: [
            "Devis Gratuit",
            "Techniciens certifiés APSAD R4",
            "Extincteurs NF EN 3",
            "Registre de sécurité remis",
            "Entreprise, ERP & Copropriété"
        ],

        stations: [],
        hospitals: [],
        neighborhoods: target.top_places,

        points_of_interest: {
            hotels: [],
            nightlife: [],
            monuments: [],
            parking_difficulty: "High Demand"
        },

        // Identité administrative réelle (API Découpage administratif)
        insee: target.insee,
        epci: target.epci,
        population: target.population,
        deptName: target.deptName,
        regionName: target.regionName,
        zones: target.zones,

        pricing: {
            base: priceDisplay,
            description: priceDesc,
            km: 0
        },

        phoneNumber: "09 72 50 12 50",
        email: "contact@expertsecuriteincendie.fr",
        type: "PARTNER",
        targetType: "MIXED",

        meta: {
            title: target.heroTitle,
            description: uniqueMetaDescription
        }
    };
}

